### ISSUE TITLE
Allow fields to be defined as required

### ISSUE THREAD

**Issue by Timothy-D** [exeGesIS-SDM/CAMS-Desktop#30]
Allow users to define fields as 'Required' - if these aren't completed on saving the record, the user is warned

**Comment by MitchellH-ESDM** [comment]
@Timothy-D 

Added <add key="MaintConfig.RequiredFields" value="Priority#Descr#Location#User1#MaintCode#AdminArea"/>
and <add key="InfraConfig.RequiredFields" value="Priority#Parish#Location#User1#MaintCode#AdminArea"/>

to Cams.exe.config

This did not make the fields required.

**Comment by Timothy-D** [comment]
Hi @MitchellH-ESDM I can't see the bits you've added in the comment above. Please can you confirm and also the version number & date of the exe you're using?

**Comment by MitchellH-ESDM** [comment]
@Timothy-D 
 Date of exe is 16/09/2021 12:09
The Version is 7.2.3.21889 as it says in the Help-> about section

I added these to the config 

add key="MaintConfig.RequiredFields" value="Priority#Descr#Location#User1#MaintCode#AdminArea"/
add key="InfraConfig.RequiredFields" value="Priority#Parish#Location#User1#MaintCode#AdminArea"/

**Comment by Timothy-D** [comment]
OK, a couple of things here:
1. You need the most recent exe dated 02/11 from "S:\ESDM Installs\CAMS\CAMS7.2.3\Test\Cams.exe" - this functionality isn't in the build you're using
2. Priority, Location & MaintCode fields don't exist in Infra, so that won't work. See the attached document for valid fields (the master for this is in the CamsDocs GIT repo)
[CAMS Desktop Required Fields.docx](https://github.com/exeGesIS-SDM/CAMS-Desktop/files/7521582/CAMS.Desktop.Required.Fields.docx)

**Comment by MitchellH-ESDM** [comment]
**MH Test Pass** For Route, WholeRoute, Maint & Infra, configure fields as required.

**MH Test Pass** Check that you cannot save from teh button when one or more of these are empty

**MH Test Fail:** Message has multiple commas sepearating the required fields (Photo Attatched)

![image](https://user-images.githubusercontent.com/84922421/142001964-b7b88eeb-49e3-4dfe-a1cc-60399698eaea.png)

**MH Test Pass** Check that nothing prevents workign within the record, even if these fields are empty (eg make sure you can add condition records & go to the map)
**MH - Unfamiliar in how to check UDFS, need guidance**
**MH Test Pass** Check without the setting records can be saved with as before

**Comment by Timothy-D** [comment]
Hi @MitchellH-ESDM -
**Re messaging**: agree this is a bug. Please can you let me know the config setting you were using and which fields were empty when you saved, and I'll take a look?
**Re User Fields**: This is a more complex area and not easy to explain over the message board. Can we have a session Wed or Thur this week and we can look at it together? - that'll probably be more efficient.

**Comment by MitchellH-ESDM** [comment]
Hi @Timothy-D 
**Re Messaging** The config setting for that specific missing data message was<add key="MaintConfig.RequiredFields" value="#MaintPriority#Descr"/> on Line 165 from Instance 1 exe.config. No matter what other fields were filled in, the amount of commas does not change in the message.

**Re User Fields** Yes please, i'm guessing thursday would be better now, but whenever you have time a session would be great.

**Comment by Timothy-D** [comment]
@MitchellH-ESDM  - when you say "Instance 1 exe.config", which server is this? Looking on the RDS-Demo-CAMS server (the only one I know of with the "Instance1" setup, the "RequiredFields" key doesn't exist in the config. Any chance you could paste the key you're using here, please?

**Comment by MitchellH-ESDM** [comment]
Sorry @Timothy-D I have added it in Instance 1 on CAMS-Test-VM7

TheKey is add key="MaintConfig.RequiredFields" value="#MaintPriority#Descr"/ On Line 165

**Comment by Timothy-D** [comment]
The issue here is the leading "#" at the beginning of the string. If you remove this the problem should go away. Don't think any code changes are needed here.

**Comment by MitchellH-ESDM** [comment]
@Timothy-D Test Passed

**Comment by Timothy-D** [comment]
OK
