### ISSUE TITLE
CAMS Desktop: Not currently handling storage of photos upon import from CAMS Mobile for Land records with no Admin Area associations

### ISSUE THREAD

**Issue by am-esdm** [exeGesIS-SDM/CAMS-Desktop#47]
Presume this only happens when using the "add key="WebDataLogConfig.SavePhotosPath" value="T:\ExampleFolderPath\\%AdminArea%"" config key with the %AdminArea% placeholder (haven't tested this without that config placeholder entry), based on the following logic.

Currently get the following messages (tested in CAMS v7.2.1) after importing the associated Import Review record, presumably because the %AdminArea% placeholder doesn't produce a folder name when the Land record doesn't have any associated Admin Area.

Message 1:

---------------------------
Photo processing error
---------------------------
Unable to save the image to F:\CAMSPhotos\\%AdminArea%\Land_00001_20190930_1.jpg. Please check the SavePhotosPath in the config file is correct.

CAMS will attempt to save the photo to your %Temp% folder, you may need to move it via ThumbsPlus manually when processing is complete
---------------------------
OK   
---------------------------

Message 2:

---------------------------
CAMS
---------------------------
An error was encountered processing the photo(s) for Holding record 13466
---------------------------
OK   
---------------------------

**Comment by am-esdm** [comment]
Config entry is this particular case was valid (<add key="WebDataLogConfig.SavePhotosPath" value="F:\CAMSPhotos\%AdminArea%"/>) and other photos for other record types are importing fine

**Comment by richardcesdm** [comment]
I have tested this in v7.2.3 but unfortunately I am still getting the 'An error was encountered processing the photo(s) for Holding record' error message when processing a land update and the photo fails to link. 

An example holdingID that has a photo in the webholdingdocuments table is in the cams_dev_master db with holdingID: 1853

**Comment by Timothy-D** [comment]
I have processed the Land record in the dev master database without error, so not sure what is happening here.
I have built a modified exe ("S:\ESDM Installs\CAMS\CAMS7.2.3\Test\Cams.exe") with more logging in this area - this may help if it's run with logging set to trace.

Basic things which you have probably checked but it would be good to confirm in this thread:
- Do you have a valid LL editor licence?
- What is the value of the "WebDataLogConfig.SavePhotosPath" config key?
- Is this a valid path?
- Do you have full permission to it
- Have files been catalogued in this location before?

**Comment by richardcesdm** [comment]
I have retested this and looks like it was a testing error (had not catalogued a file at the quickupload location). Having corrected the problem it looks to be working nicely.
