### ISSUE TITLE
Import review improvements (structure bug)

### ISSUE THREAD

**Issue by richardcesdm** [exeGesIS-SDM/CAMS-Desktop#52]
I will use this task to record any potential improvements / fixes relating to the Import Review form

1) (FIX) Fix problem where form structure often gets lost (this was fixed on the 'unprocessed' form but is still a problem on the 'processed' form.

2) (IMPROVEMENT) Allow users to reset the status of rejected records to allow them to be processed again.

**Comment by richardcesdm** [comment]
Sorry to raise this so late but it looks like it was raised originally some time ago and has been overlooked. The structure of the 'Show processed' section of the Import Review continues to get lost whenever CAMS closes down. This was a problem that effected the 'Unprocessed' side of the form in the past and was fixed. Can we apply the same fix to the 'Processed' side of the form too? Users who do a lot of processing will frequently have to deal with the 'Processed' side of the form but often are unaware they need to click the icon to reset it's structure so will just continue to use with the unintended structure. For reference, the 'Processed' form typically looks like this upon opening (note columns extend off the side of the screen):

![image](https://user-images.githubusercontent.com/24268198/151137102-c4960477-45b1-40ee-9b68-99281a19e306.png)

It should look like this: 

![image](https://user-images.githubusercontent.com/24268198/151137193-2f825414-ad99-423b-bbb7-9c6108d23351.png)


If this cannot be included in 7.2.3 I would highly recommend it is included in the next version.

**Comment by Timothy-D** [comment]
This has now been fixed. The problem with the processed grid was that if the layout XML was saved before the grid had been properly instantiated (eg by clicking refresh when the processed grid hadn't been opened) then the saved XML did not contain any data and so the grid reverted. I have tried to capture the places where the XML is saved to check that the grid has been instantiated and have also added a check on opening the processed grid that the XML is valid and deletes the file if it isn't.

"un-rejecting" of a record has been implemented through the grid button in the processed grid.

This will need to be properly tested

**Comment by richardcesdm** [comment]
Tested structure reset issue and working nicely, nice spot Timothy the key step was hitting that refresh button prior to opening the 'processed' side of the form. 

Also tested the 'un-reject' option, was able to use the grey button at the end of the row to unreject / reset a record successfully.
