### ISSUE TITLE
Investigate 64-bit

### ISSUE THREAD

**Issue by Timothy-D** [exeGesIS-SDM/CAMS-Desktop#59]
HBSMR uses 64-bit Office & MapLink, which leads to conflict with CAMS if they need to be installed together.
We have memory problems with lots of photos on a record (see #58) and also with reports.

Investigate whether we can move CAMS to 64-bit and what the implications of this will be and the time required.

**Comment by PRMills** [comment]
CAMS desktop seems to convert to 64bit seamlessly, however crystal reports needs updating. So having registered with SAP Crystal Reports and gone to the 'free software download' site, get 'You are not authorized to download this file', for 'SAP Crystal Reports for Visual Studio (SP31) runtime engine for .NET framework MSI (64-bit)' - which i guess is the one i need ...

**Comment by MitchellH-ESDM** [comment]
I need Guidance to what needs testing for this issue @Timothy-D

**Comment by Timothy-D** [comment]
Hi @MitchellH-ESDM , I'm in the process of setting up a 64-bit test environment on the MapLink Test VM 7 machine, but there isn't really a 64-bit test release yet and it will need different versions of LibraryLink, MapLink & Crystal. 
There isn't really a single test for 64-bit as such, it will just be a case of running through general testing on the 64-bit platform. So probably best to focus on the other specific items first.

**Comment by Timothy-D** [comment]
There is a 64-bit installer in S:\ESDM Installs\CAMS\CAMS7.2.3\Test - see the ReadMe doc in this folder.

I have been able to generate a map report for over 1,000 links and save it without error, which I don't think would have worked before. So I think this is an improvement. My general testing so far has not hit any issues
