### ISSUE TITLE
Issue actions not being signed off when issue is closed

### ISSUE THREAD

**Issue by Timothy-D** [exeGesIS-SDM/CAMS-Desktop#60]
Hampshire have reported an issue with Actions not being correctly signed off when an issue is closed. The work flow they are following is as follows: 
1. Lisa signs off issue as resolved
2. This prompts an email box to appear – which Lisa updates
3. Under   Actions a new entry of Email is automatically created
4. Issue is signed off but Action to Email is not.
5. Evidence suggest that email is sent, it is just the update against the action that isn’t working.

Need to check exactly what is happening here. Likely to be the order of what is happening (resolving the issue triggers the alert but the issue is already signed off). If this uses the standard AlertOfficer function then it should be signed off when sent. Needs further investigation with actual data.

**Comment by Timothy-D** [comment]
@KathrynSteemson what is the status with this?

**Comment by KathrynSteemson** [comment]
No further feedback from the client. With that in mind I think we should just leave as is and move on....

**Comment by Timothy-D** [comment]
Given the above, abandoning this one for this project.
