### ISSUE TITLE
User Field Improvements

### ISSUE THREAD

**Issue by Timothy-D** [exeGesIS-SDM/CAMS-Desktop#63]
These improvements will make user fields more suitable for CAMS Pro and provide better functionality for users.

Allow Sorting by using the {Entity}UserFieldsDefinition.SortOrder field - sort should respect tabs

Remove the requirement for multiple UserFieldLabelN columns in eg infraTypeLUT and use {Entity}UserFieldsDefinition.ShowForTypeValues to control display of UDFs (on/off) for Route (by Route.Status), infra (byt Infra.Type), Maint (by Maint.Type) & RouteSurface (by RouteSurface.Type).
Data migration will be needed, but this work will overlap with Cams Pro

**Comment by Timothy-D** [comment]
Sort Order implemented - this shouldn't worry about the tabs.

CAMS Pro - compatible method of allowing different UDFs for different record types has been implemented - note this replaces the idea of recycling UDFs - for the folowing entities:
- Maint (based on MaintType)
- Infra (based on InfraType)
- Surface (based on SurfaceType)
- Route/WholeRoute (based on either Status or Legal Type - controlled by config setting `RouteConfig.UdfTypeField`

Needs testing
1. Test with correct config that the right UDFs display for the right records
2. Migration of recycled udfs, should be handled by scripts: need to have some set up and make sure after migration the correct ones show
3. When changing type, make sure UDFs avialable change appropriately
4. Make sure all UDF data are correctly saved

**Comment by richardcesdm** [comment]
I have run scripts against main dev database plus 1 other client so far (OCC) without any obvious errors or problems - may benefit from further testing by others

**Comment by Timothy-D** [comment]
Tested - OK
