### ISSUE TITLE
Erroneous Maint.LogBy updates

### ISSUE THREAD

**Issue by Timothy-D** [exeGesIS-SDM/CAMS-Desktop#66]
RC reports LogBy   getting updated when processing records from Web Data Log:

> Based on my testing it seems that if the current logged in CAMS Desktop user has a valid Officer linked to them then CAMS Desktop will always update the Maint.LogBy field with the Currently logged in Officer when an update to an issue is processed from the Import Review form. This applies for all issue updates including public and callcentre fault reports (including those duplicate reports that get associated with existing issues), officer and volunteer reports from CAMS Web and officer reports from CAMS Mobile. 
> 
> To put it another way I will describe the steps to replicate: 
> 
> 1) Create issue in CAMS Desktop with Maint.LogBy value of 'Peter Cook' 
> 2) Login to CAMS Web or CAMS Mobile as 'test_officer' and update this issue 
> 3) Login to CAMS Desktop as 'Arthur Rake' and process the updated issue submission 
> 4) Maint.LogBy is now updated to say 'Arthur Rake' 
> 
> Hopefully from that you can see that we're effectively making the person who processed the latest update to the issue liable for this issue, rather than the person who first recorded it or the person who has actually provided the latest update from Web or Mobile. 
> 
> I also found the following is possible with submissions that come from CAMS Mobile:
> 
> 1) Create issue in CAMS Desktop with Maint.LogBy value of 'Peter Cook' 
> 2) Login to CAMS Mobile as 'test_officer' and update this issue 
> 3) Login to CAMS Desktop as a 'non officer' user (i.e. a CAMS Desktop user with no valid officer value in sysUsers.Officer) and process the updated issue submission 
> 4) Maint.LogBy is now updated to say 'test_officer' 
> 
> This is possible because submissions from CAMS Mobile contain a Maint.LogBy value in the xml, but this is the value represents the current logged in CAMS Mobile user, not necessarily the same person who first logged the issue. 

Need to identify which submissions are affected here. Normally Log By should not update once the original record is saved. This is likely to be a case of removing from procedures and/or XSLT.

**Comment by Timothy-D** [comment]
@richardcesdm From the code, updates to LogBy would happen via the procedure. This means that the data has to be present in the XML and the relevant procedure has to include the statement to update the final database table. If the incoming XML contains `%LogBy%` then CAMS will update this with the ID of the logged-in user processing the record.

From this, there are a couple of things we need to do:

1. For Maint_Update, this can be handled in the stored procedure (usp_Process_Maint_Update)
2. For anything that uses the "generic" procedures, this must be handled in the input XML so it does not include a LogBy
3. What other submission types / procedures are affected?

**Comment by Timothy-D** [comment]
@richardcesdm are you happy with this? can we sign off?

**Comment by richardcesdm** [comment]
spoke to TD and did further testing with this to try and cover all possible scenarios where a public or trusted user could insert or update an issue. Quite a few variations but believe I have covered everything so will mark this as complete.
