### ISSUE TITLE
Update default XSL files to use default CAMS install location

### ISSUE THREAD

**Issue by richardcesdm** [exeGesIS-SDM/CAMS-Desktop#78]
If there is any chance we could do this then it is one less thing to do when we are setting up new CAMS environments with new XSLs. I can supply modified files if that would help but they just need to be included in the installer package. Currently the defaults always need to be changed.

Relavant files in question: 
XSL\HeaderTemplate.xsl 
XSL\jQuery\jquery.lightbox-0.5.min.js

Also optionally: 
XSL\ContractDetail.xsl
XSL\EnfDetail.xsl
XSL\FieldworkDetail.xsl
XSL\FlyTippingDetail.xsl
XSL\InfraDetail.xsl
XSL\JobDetail.xsl
XSL\LandDetail.xsl
XSL\LegalDetail.xsl
XSL\MaintDetail.xsl
XSL\NewDetail.css
XSL\ProjectDetail.xsl
XSL\RouteDetail.xsl
XSL\RouteGroupDetail.xsl
XSL\StreetViewReadMe.txt
XSL\SurfaceDetail.xsl
XSL\WholeRouteDetail.xsl

File paths within the files above should reference the typical CAMS Desktop default install location i.e. C:\Program Files (x86)\ESDM\CAMS

**Comment by Timothy-D** [comment]
Some things are best in a shared location so don't have to be modified for each user, but these will need changing regardless of what the default location is.
Where possible, I think we're best using relative paths to eg HeaderTemplate.xsl as these will change and everyone needs the shared one (in some cases relative paths aren't possible).
You just need to make sure that the files in GIT camsdocs are correct.

The other thing that is worth looking at is making sure all the streetview stuff is removed as we can't use this any more

**Comment by richardcesdm** [comment]
I have checked and can confirm the following default files present in the cams docs repo xsl folder use the default CAMS install location

XSL\HeaderTemplate.xsl
XSL\jQuery\jquery.lightbox-0.5.min.js

I believe the streetview stuff is not present now but will try to double check in the future

**Comment by Timothy-D** [comment]
Updated for 64-bit and removed streetview. Will be included when the installer is next rebuilt.
