### ISSUE TITLE
Increase UDF label width size (OR set max label width = the longest label value)

### ISSUE THREAD

**Issue by richardcesdm** [exeGesIS-SDM/CAMS-Desktop#79]
Current problem: 
It has been noted by clients that the current UDF label width in CAMS Desktop can be too short for new UDF values with longer names (e.g. in cases where units need to be recorded labels can be long). 

Proposed solution: 
Either increase the default label width for all UDFs be a set amount (suggestion: double the current width) 
OR find some way to dynamically change the label width so that it is always as long as the longest value. This would save on wasted space. but probably not worth the extra time to do (but might be nice if it is quick). 

Low priority.

**Comment by Timothy-D** [comment]
Tested CAMS 7.2.3 x64 with route, infra & maint - all OK.
Do NOT recommend setting this for InfraCondition or RouteCondition UDFs as the forms are narrow
