### ISSUE TITLE
OfficerLUT requires restart message appears at unexpected times

### ISSUE THREAD

**Issue by richardcesdm** [exeGesIS-SDM/CAMS-Desktop#82]
Seems like this message is getting triggered when opening the contact form for Officers, or perhaps just when opening the contact form via the web users contact button as per the screenshot below. Either way it seems to be displaying more than necessary. Is a restart even required anymore? 

![image](https://user-images.githubusercontent.com/24268198/139467157-e5b06b21-aafe-4489-84ca-3190211b6c7e.png)

**Comment by MitchellH-ESDM** [comment]
@Timothy-D  Test Passed

**Comment by Timothy-D** [comment]
OK
