### ISSUE TITLE
LibraryLink error message displays on Import Review for users without a LibraryLink licence for all records (Including those without photos) 

### ISSUE THREAD

**Issue by richardcesdm** [exeGesIS-SDM/CAMS-Desktop#83]
Not sure if this has been logged elsewhere but can't find any record of it so will repeat here: 

There is a problem in v7.2.2 when processing records on import review without a librarylink licence active. The following message will always display: 

![image](https://user-images.githubusercontent.com/24268198/139884577-36dbf901-69c8-404e-b5f6-73822194913f.png)

followed by 

![image](https://user-images.githubusercontent.com/24268198/139884763-43e4f9fa-e21a-4efe-acfb-75a0a45da1c7.png)

After these messages the record processes through successfully, but none the less these messages should only display for records that actually have a photo attached, not for all records. 

This will need to be tested using a machine with CAMS Desktop present but no LibraryLink installed / active.

**Comment by Timothy-D** [comment]
done

**Comment by MitchellH-ESDM** [comment]
@Timothy-D 

Test Passed, Message only displays on records with photos attached
